version: '3.8'

services:
  frontend:
    build: .
    container_name: gps-frontend-dev
    ports:
      - "85:80"           # http://localhost:4200
    environment:
      # Angular necesita saber dónde vive la API en local:
      API_BASE_URL=http://190.13.177.173:8080
