version: '3.8'
services:
  # Backend principal - agrega aquí tu imagen de backend
  backend:
    # image: tu-backend-image:latest  # Reemplaza con tu imagen real
    container_name: gps-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/gps_db
    networks:
      - backend-net
    depends_on:
      - postgres
    # Comentar esta línea hasta que tengas la imagen del backend
    # Si no tienes backend, usaremos nginx para simular respuestas
    command: ["echo", "Backend container - replace with actual backend image"]
    
  dashboard:
    # image: tu-dashboard-image:latest  # Reemplaza con tu imagen real del dashboard
    container_name: microservicio-dashboard
    ports:
      - "8085:8085"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/gps_db
    networks:
      - backend-net
    depends_on:
      - postgres
    # Comentar esta línea hasta que tengas la imagen del dashboard
    command: ["echo", "Dashboard container - replace with actual dashboard image"]
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gps-frontend
    ports:
      - "8005:80"
    environment:
      - API_BASE_URL=http://gps-backend:8080/api
    networks:
      - backend-net
    depends_on:
      - backend
      - dashboard
      
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=gps_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - backend-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend-net:
    driver: bridge
    
volumes:
  postgres_data: 