version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gps-frontend
    ports:
      - "8005:80"
    environment:
      - API_BASE_URL=http://gps-backend:8080
    networks:
      - backend-net

networks:
  backend-net:
    external: true 